// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// GetBinaryDosageInfoC
Rcpp::List GetBinaryDosageInfoC(const std::string& bdFilename, const std::string& famFilename, const std::string& mapFilename);
RcppExport SEXP _BinaryDosage_GetBinaryDosageInfoC(SEXP bdFilenameSEXP, SEXP famFilenameSEXP, SEXP mapFilenameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type bdFilename(bdFilenameSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type famFilename(famFilenameSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type mapFilename(mapFilenameSEXP);
    rcpp_result_gen = Rcpp::wrap(GetBinaryDosageInfoC(bdFilename, famFilename, mapFilename));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_BinaryDosage_GetBinaryDosageInfoC", (DL_FUNC) &_BinaryDosage_GetBinaryDosageInfoC, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_BinaryDosage(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
