// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// OpenVCFFile
Rcpp::List OpenVCFFile(Rcpp::StringVector& rFilename);
RcppExport SEXP _BinaryDosage_OpenVCFFile(SEXP rFilenameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::StringVector& >::type rFilename(rFilenameSEXP);
    rcpp_result_gen = Rcpp::wrap(OpenVCFFile(rFilename));
    return rcpp_result_gen;
END_RCPP
}
// ReadVCFValues
int ReadVCFValues(std::string& filename, Rcpp::NumericMatrix& values, Rcpp::IntegerVector& snps, Rcpp::IntegerVector& subjects, Rcpp::NumericVector& indices, Rcpp::StringVector& formats);
RcppExport SEXP _BinaryDosage_ReadVCFValues(SEXP filenameSEXP, SEXP valuesSEXP, SEXP snpsSEXP, SEXP subjectsSEXP, SEXP indicesSEXP, SEXP formatsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string& >::type filename(filenameSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix& >::type values(valuesSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector& >::type snps(snpsSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector& >::type subjects(subjectsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector& >::type indices(indicesSEXP);
    Rcpp::traits::input_parameter< Rcpp::StringVector& >::type formats(formatsSEXP);
    rcpp_result_gen = Rcpp::wrap(ReadVCFValues(filename, values, snps, subjects, indices, formats));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_BinaryDosage_OpenVCFFile", (DL_FUNC) &_BinaryDosage_OpenVCFFile, 1},
    {"_BinaryDosage_ReadVCFValues", (DL_FUNC) &_BinaryDosage_ReadVCFValues, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_BinaryDosage(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
