# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

OpenVCFFile <- function(rFilename) {
    .Call(`_BinaryDosage_OpenVCFFile`, rFilename)
}

ReadVCFValues <- function(filename, values, snps, subjects, indices, formats) {
    .Call(`_BinaryDosage_ReadVCFValues`, filename, values, snps, subjects, indices, formats)
}

WriteBinaryDosageBaseHeader <- function(filename, format, subformat) {
    .Call(`_BinaryDosage_WriteBinaryDosageBaseHeader`, filename, format, subformat)
}

WriteBinaryDosageHeader3A <- function(filename, numSubjects) {
    .Call(`_BinaryDosage_WriteBinaryDosageHeader3A`, filename, numSubjects)
}

WriteBinaryDosageHeader3B <- function(filename, md5samples, md5SNPs) {
    .Call(`_BinaryDosage_WriteBinaryDosageHeader3B`, filename, md5samples, md5SNPs)
}

WriteBinaryDosageHeader4A <- function(filename, numSubjects, numSNPs) {
    .Call(`_BinaryDosage_WriteBinaryDosageHeader4A`, filename, numSubjects, numSNPs)
}

WriteBinaryDosageHeader4B <- function(filename, numSubjects, numSNPs) {
    .Call(`_BinaryDosage_WriteBinaryDosageHeader4B`, filename, numSubjects, numSNPs)
}

WriteBDGroups <- function(filename, groups) {
    .Call(`_BinaryDosage_WriteBDGroups`, filename, groups)
}

WriteBinaryDosageData <- function(filename, dosage, usdosage, base) {
    .Call(`_BinaryDosage_WriteBinaryDosageData`, filename, dosage, usdosage, base)
}

WriteBinaryP1P2Data <- function(filename, p1, p2, usp1, usp2, base) {
    .Call(`_BinaryDosage_WriteBinaryP1P2Data`, filename, p1, p2, usp1, usp2, base)
}

