# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ReadBinaryDosageBaseHeader <- function(filename) {
    .Call(`_BinaryDosage_ReadBinaryDosageBaseHeader`, filename)
}

ReadBinaryDosageHeader3A <- function(filename) {
    .Call(`_BinaryDosage_ReadBinaryDosageHeader3A`, filename)
}

ReadBinaryDosageHeader3B <- function(filename) {
    .Call(`_BinaryDosage_ReadBinaryDosageHeader3B`, filename)
}

ReadBinaryDosageHeader4A <- function(filename) {
    .Call(`_BinaryDosage_ReadBinaryDosageHeader4A`, filename)
}

ReadBinaryDosageHeader4B <- function(filename) {
    .Call(`_BinaryDosage_ReadBinaryDosageHeader4B`, filename)
}

ReadBDIndicesS4 <- function(filename, numSNPs, indexStart) {
    .Call(`_BinaryDosage_ReadBDIndicesS4`, filename, numSNPs, indexStart)
}

ReadBinaryData11 <- function(filename, headersize, snp, dosage, usdosage, base) {
    .Call(`_BinaryDosage_ReadBinaryData11`, filename, headersize, snp, dosage, usdosage, base)
}

ReadBinaryData12 <- function(filename, headersize, snp, dosage, p0, p1, p2, us, base) {
    .Call(`_BinaryDosage_ReadBinaryData12`, filename, headersize, snp, dosage, p0, p1, p2, us, base)
}

OpenVCFFile <- function(rFilename) {
    .Call(`_BinaryDosage_OpenVCFFile`, rFilename)
}

ReadVCFValues <- function(filename, values, snps, subjects, indices, formats) {
    .Call(`_BinaryDosage_ReadVCFValues`, filename, values, snps, subjects, indices, formats)
}

WriteBinaryDosageBaseHeader <- function(filename, format, subformat) {
    .Call(`_BinaryDosage_WriteBinaryDosageBaseHeader`, filename, format, subformat)
}

WriteBinaryDosageHeader3A <- function(filename, numSubjects) {
    .Call(`_BinaryDosage_WriteBinaryDosageHeader3A`, filename, numSubjects)
}

WriteBinaryDosageHeader3B <- function(filename, md5samples, md5SNPs) {
    .Call(`_BinaryDosage_WriteBinaryDosageHeader3B`, filename, md5samples, md5SNPs)
}

WriteBinaryDosageHeader4A <- function(filename, numSubjects, numSNPs) {
    .Call(`_BinaryDosage_WriteBinaryDosageHeader4A`, filename, numSubjects, numSNPs)
}

WriteBinaryDosageHeader4B <- function(filename, numSubjects, numSNPs) {
    .Call(`_BinaryDosage_WriteBinaryDosageHeader4B`, filename, numSubjects, numSNPs)
}

WriteBDGroups <- function(filename, groups) {
    .Call(`_BinaryDosage_WriteBDGroups`, filename, groups)
}

WriteBDGroups2 <- function(filename, groups) {
    .Call(`_BinaryDosage_WriteBDGroups2`, filename, groups)
}

WriteBDFamilyInfoC <- function(filename, numSub, sid, fid, numSubLoc, suboffsetLoc, snpoffsetLoc) {
    .Call(`_BinaryDosage_WriteBDFamilyInfoC`, filename, numSub, sid, fid, numSubLoc, suboffsetLoc, snpoffsetLoc)
}

WriteBDSNPInfoC <- function(filename, numSNPs, snpid, chromosome, location, reference, alternate, aaf, maf, avgCall, rsq, numSNPloc, snpOptionsLoc, snpOffsetLoc, nextOffsetLoc) {
    .Call(`_BinaryDosage_WriteBDSNPInfoC`, filename, numSNPs, snpid, chromosome, location, reference, alternate, aaf, maf, avgCall, rsq, numSNPloc, snpOptionsLoc, snpOffsetLoc, nextOffsetLoc)
}

WriteBDIndexArray3_4 <- function(filename, numSNPs) {
    .Call(`_BinaryDosage_WriteBDIndexArray3_4`, filename, numSNPs)
}

WriteBDIndexArray4_4 <- function(filename, numSNPs, indexoffsetLoc, dosageoffsetloc) {
    .Call(`_BinaryDosage_WriteBDIndexArray4_4`, filename, numSNPs, indexoffsetLoc, dosageoffsetloc)
}

WriteBinaryDosageData <- function(filename, dosage, usdosage, base) {
    .Call(`_BinaryDosage_WriteBinaryDosageData`, filename, dosage, usdosage, base)
}

WriteBinaryP1P2Data <- function(filename, p1, p2, usp1, usp2, base) {
    .Call(`_BinaryDosage_WriteBinaryP1P2Data`, filename, p1, p2, usp1, usp2, base)
}

