# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

GetBinaryDosageInfoC <- function(bdFilename, famFilename, mapFilename, index) {
    .Call('_BinaryDosage_GetBinaryDosageInfoC', PACKAGE = 'BinaryDosage', bdFilename, famFilename, mapFilename, index)
}

GetSNPValuesC <- function(bdFilename, subVec, snpVec, indices, valueMatrix) {
    .Call('_BinaryDosage_GetSNPValuesC', PACKAGE = 'BinaryDosage', bdFilename, subVec, snpVec, indices, valueMatrix)
}

GetVCFSNPValues <- function(vcfFilename, subVec, snpVec, indices, valueMatrix) {
    .Call('_BinaryDosage_GetVCFSNPValues', PACKAGE = 'BinaryDosage', vcfFilename, subVec, snpVec, indices, valueMatrix)
}

GetVCFHeaderC <- function(vcfFile) {
    .Call('_BinaryDosage_GetVCFHeaderC', PACKAGE = 'BinaryDosage', vcfFile)
}

GetVCFSNPInfoC <- function(filename, startData, reserve) {
    .Call('_BinaryDosage_GetVCFSNPInfoC', PACKAGE = 'BinaryDosage', filename, startData, reserve)
}

